name: HealthCheck

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - name: Install packages
        run: npm ci
      - name: Update .env
        run: cat .env.example | envsubst > .env
      - name: Run health check
        run: npm run test:health-check
