name: HealthCheck

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 15 * * *'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - name: Install packages
        run: yarn
      - name: Create .env
        run: |
          touch .env
          echo USERNAME=${{ secrets.USERNAME }} >> .env
          echo PASSWORD=${{ secrets.PASSWORD }} >> .env
          echo CHECKIN_CRON_RULE=${{ secrets.CHECKIN_CRON_RULE }} >> .env
          echo CHECKOUT_CRON_RULE=${{ secrets.CHECKOUT_CRON_RULE }} >> .env
      - name: Run health check
        run: yarn test:health-check
